PUSH_NOTIF_MESSAGE_TEXT = "We have some new tasks assigned to you, do you want to work on them?"
PUSH_NOTIF_RESPONSE_YES_TEXT = "Yes, sure"
PUSH_NOTIF_RESPONSE_NO_TEXT = "No, thank you"
PUSH_NOTIF_RESPONSE_YES_CALLBACK = "PUSH_NOTIF_RESPONSE_YES"
PUSH_NOTIF_RESPONSE_NO_CALLBACK = "PUSH_NOTIF_RESPONSE_NO"

